[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
lib_deps = 
	dashio-connect/DashioNano33BLE@^1.2.3
	contrem/arduino-timer@^3.0.1
	arduino-libraries/Servo@^1.2.2
lib_ldf_mode = deep
monitor_speed = 115200
